import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiTypescript,
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiTailwindcss,
  SiMongodb,
  SiFirebase,
  SiDocker,
  SiKubernetes,
  SiVercel,
  SiCplusplus,
  SiGo,
  SiFlask,
  SiDjango,
  SiGit,
  SiGithub,
  SiGitlab,
  SiPostman,
  SiLinux,
} from "react-icons/si";

import { FaDiscord, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaDatabase } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: SiGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  database: FaDatabase,
  python: SiPython,
  typescript: SiTypescript,
  react: SiReact,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastapi: SiFastapi,
  tailwindcss: SiTailwindcss,
  mongodb: SiMongodb,
  firebase: SiFirebase,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  vercel: SiVercel,
  cplusplus: SiCplusplus,
  go: SiGo,
  flask: SiFlask,
  django: SiDjango,
  git: SiGit,
  gitlab: SiGitlab,
  postman: SiPostman,
  linux: SiLinux,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
